apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-ephemeral-api-role
rules:
# Permissions for EphemeralApplications CRD
- apiGroups:
  - ephemeral.argo.io
  resources:
  - ephemeralapplications
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ephemeral.argo.io
  resources:
  - ephemeralapplications/status
  verbs:
  - get
  - update
  - patch

# Permissions for TokenReview (authentication)
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create

# Read namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list

# Read pods for logs
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-ephemeral-api-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-ephemeral-api-role
subjects:
- kind: ServiceAccount
  name: argo-ephemeral-api
  namespace: argo-ephemeral-operator-system

