apiVersion: ephemeral.argo.io/v1alpha1
kind: EphemeralApplication
metadata:
  name: test-guestbook
spec:
  repoURL: https://github.com/argoproj/argocd-example-apps.git
  
  path: guestbook
  
  targetRevision: HEAD
  
  expirationDate: "2025-11-21T15:59:00Z"
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

