apiVersion: ephemeral.argo.io/v1alpha1
kind: EphemeralApplication
metadata:
  name: example-with-secrets
  namespace: default
spec:
  repoURL: https://github.com/argoproj/argocd-example-apps.git
  path: guestbook
  targetRevision: HEAD
  
  expirationDate: "2025-11-21T14:45:00Z"
  
  # Copy secrets from shared namespaces
  # Your deployments should reference these secrets (defined in your Git repo)
  secrets:
  - name: postgres-credentials
    values:
      username: postgres
      password: postgres
    # sourceNamespace: shared-secrets
  
  - name: api-keys
    sourceNamespace: shared-secrets
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

